theme: yefeme
title: The Musings of Yefim Vedernikoff
author: Yefim Vedernikoff
email: hi@yef.im
description: >
  This is the place where I gather my scrambled thoughts into words.
url: "https://yef.im"
twitter_username: yefim
github_username: yefim
permalink: /:title
cf_images_account_hash: xi1VyDMD-A_pDPckxeHwDA
cf_images_variants:
  thumb: thumb
  xl: xl
collections:
  shoots:
    output: true
    permalink: /portfolio/:name

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
markdown: kramdown
feed:
  collections:
    - shoots
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
